### ISSUE TITLE
My last thoughts

### ISSUE THREAD

**Issue by vladfaust** [vladfaust/awesome-crystal#1]
Looks like I've got muted in #222 and awesome-crystal itself. It's a bit of childish to mute a person which has another point of view. However, this is my comment I intended to leave:

@veelenga, we're not nurses. This is a curated list of the best Crystal libraries, not a playground.

#212 is not a similar example, because JWT is a standard and community's JWT is fully compliant with it (except RSA, which we do not have appropriate candidate yet), while I18n is not standardized and I've offered a different approach (mostly for extensionality). Also all existing I18n libraries were not maintained, while JWT has the last commit dated September 2nd, which is fresh for me. In addition, I was okay to leave the original shard as is, and it was our cooperative decision to remove it.

> @drujensen Crystal is not so popular as javascript and probably will never be. I think we don't have to worry about npm hell, at least for now.

I strongly disagree with you. I'm sure Crystal will be essential language in the nearest future and it's our responsibility to keep it clean from the very beginning.

@RX14 you're right about me sometimes being too aggressive, however, I'm always trying to verify my comments with arguments. Regarding to #222, I have four points, why is it non-constructive?

Summing it up, I'm against the position like _everyone, push your Crystal sandbox code to the AWESOME BEST SHARDS list_. We could create another repository for this, though.

**Comment by A-Large-Can-Of-Worms** [comment]
This is a nice example of the topic we have these days! This issue is useless due to:
- No new functionality for existing `awesome-crystal` environment
- Even less respect for fellow contributors
- Bad drama
- Lesser community

The only difference I see is constructive vs non-constructive criticism. This may be a better practice, SOLID etc., but you seem to think that non-constructive criticism is indeed constructive, and then take it personally when you're called out on such.

**Comment by vladfaust** [comment]
@HereForTheMemes nice and funny reply! _(not really)_

Let's imagine a situation when you have a girlfriend. She is very beautiful.  You're a gym guy, she's pretty fit too for now. But one day you wake up and see a fat monster near you in a bed. You realize that something's gone wrong. Basically, you let her eat everything she gets from her fans (yes, she has many). Damn it. Your and her lives are ruined.

What you could do before is stopping her from eating that garbage. You would want her to eat only fresh beautiful healthy fruits she finds on the trees for herself or to manually select gifts from her fans. Yes, it needs some effort, but in the future it will be better both for you and her.

Once she's starting to get fat, her friends will begin to protect her with those piggy screams. They will only see that I'm stopping her from eating everything she wants. They fill pity for those fans - like, _"They've wasted their energy on their shit gifts, but she (and we) just **have** to eat it"_. They don't see the consequences.

The truth is - you actually **can** impact your girlfriend's ration. And sooner you start better it will be.

If the community sees the average low level of shards' code, they will contribute the same trash again and again. That's my point.

Also, your _"you're just not being constructive"_ is just not constructive. Bring me a confirmation of your words - point me to my relevant replies which are based on pure emotions?

**According to your points:**

> - No new functionality for existing awesome-crystal environment

Wrong. I wish to clean it of useless shards and you can see other things I want to improve (and even to bring the new functionality) here: https://github.com/veelenga/awesome-crystal/issues/223#issuecomment-334112641

> - Even less respect for fellow contributors

Respect doesn't mean hypocrisy. If I see my girlfriend getting fat, I'll do everything to help her, because I love her. I have an enormous amount of respect to meaningful contributors, why would I to strangers with shitcode?

> - Bad drama

There are issues which have to be revealed.

> - Lesser community

Let them stay in JS, Ruby and pre-schools. Quantity is less important than quality.

**Comment by veelenga** [comment]
@vladfaust Haha, good luck 👍

Pretty sure you will manage that easily! And do not forget to announce it on Crystal ANN when it is ready 😄 🍰
