### ISSUE TITLE
My apologies.

### ISSUE THREAD

**Issue by vladfaust** [vladfaust/awesome-crystal#2]
After some time I see myself from the perspective of current time and... I was toxic to you. I got too proud of myself because of contributing into Crystal with shards which **I thought** were super important. I started to think of myself able to judge other's code. Who I am?

However, I still think I got strong arguments for my points but nobody seemed to give them any weight. I live in my own world of harmful honesty and freedom of speech, and many find this inappropriate.

I get it. For the sake of Crystal growth I will be silent on things **I find** badly developed and will try to improve them instead of writing harmful comments to the contributors.

I am sorry.

/cc @veelenga, @RX14, @rogeriozambon

**Comment by vladfaust** [comment]
Alright, I understand.

**Comment by veelenga** [comment]
Okay, you are now unblocked. Sorry for that, but you didn't give me a choice.
You are implementing good Crystal shards, keep doing that  👍
